/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaMovilVista;

import java.awt.Color;
import tiendaMovilControlador.TMControlador;
import tiendaMovilModelo.TMModelo;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Iterator;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.SoftBevelBorder;
import javax.swing.border.TitledBorder;

/**
 *
 * @author alvgonz
 */
public class TMVista extends javax.swing.JFrame {

    private TMControlador miControl;
    private TMModelo miModelo;
    /**
     * Creates new form NewJFrame
     */
    public TMVista() {
        initComponents();
        int [] pantalla={0,6};
        miModelo = new TMModelo(jSlider1.getValue(),null,null);
        miControl = new TMControlador(this,miModelo);
        
    }

      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanelPrecio = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelMarca = new javax.swing.JPanel();
        jComboBoxMarcas = new javax.swing.JComboBox();
        jPanelTamaño = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanelColor = new javax.swing.JPanel();
        jButtonColor1 = new javax.swing.JButton();
        jButtonColor3 = new javax.swing.JButton();
        jButtonColor5 = new javax.swing.JButton();
        jButtonColor2 = new javax.swing.JButton();
        jButtonColor4 = new javax.swing.JButton();
        jButtonColor6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButtonBuy = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(481, 336));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Elige las características de tu nuevo móvil"));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 427));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanelPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(255, 102, 51)), "Precio"));
        jPanelPrecio.setForeground(new java.awt.Color(204, 204, 204));
        jPanelPrecio.setLayout(new java.awt.GridBagLayout());

        jSlider1.setMajorTickSpacing(250);
        jSlider1.setMaximum(1000);
        jSlider1.setMinorTickSpacing(100);
        Hashtable labels =
        new Hashtable();
        labels.put(0, new javax.swing.JLabel("0"));
        labels.put(250, new javax.swing.JLabel("250"));
        labels.put(500, new javax.swing.JLabel("500"));
        labels.put(750, new javax.swing.JLabel("750"));
        labels.put(1000, new javax.swing.JLabel("1000"));
        jSlider1.setLabelTable(labels);

        jSlider1.setPaintLabels(true);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(400);
        jSlider1.setMinimumSize(new java.awt.Dimension(200, 40));
        jSlider1.setPreferredSize(new java.awt.Dimension(200, 40));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        jPanelPrecio.add(jSlider1, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Hasta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 55, 0, 0);
        jPanelPrecio.add(jLabel2, gridBagConstraints);

        jTextFieldPrecio.setText("400");
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 27;
        jPanelPrecio.add(jTextFieldPrecio, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(" €");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setIconTextGap(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelPrecio.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(jPanelPrecio, gridBagConstraints);

        jPanelMarca.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Marca"));
        jPanelMarca.setLayout(new java.awt.GridBagLayout());

        jComboBoxMarcas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "< Seleccione una marca >", "Samsung(5)", "Sony(5)", "Huawey(6)" }));
        jComboBoxMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanelMarca.add(jComboBoxMarcas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(jPanelMarca, gridBagConstraints);

        jPanelTamaño.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Tamaño de pantalla"));
        jPanelTamaño.setEnabled(false);
        jPanelTamaño.setPreferredSize(new java.awt.Dimension(40, 82));
        jPanelTamaño.setLayout(new java.awt.GridLayout(3, 0));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Hasta 4\"");
        jRadioButton1.setEnabled(false);
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanelTamaño.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("de 4\" a 5\"");
        jRadioButton2.setEnabled(false);
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanelTamaño.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("de 5\" a 6\"");
        jRadioButton3.setEnabled(false);
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanelTamaño.add(jRadioButton3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(jPanelTamaño, gridBagConstraints);

        jPanelColor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Color"));
        jPanelColor.setEnabled(false);
        jPanelColor.setLayout(new java.awt.GridBagLayout());

        jButtonColor1.setEnabled(false);
        jButtonColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 32, 7, 32);
        jPanelColor.add(jButtonColor1, gridBagConstraints);

        jButtonColor3.setEnabled(false);
        jButtonColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 32, 7, 32);
        jPanelColor.add(jButtonColor3, gridBagConstraints);

        jButtonColor5.setEnabled(false);
        jButtonColor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 32, 7, 32);
        jPanelColor.add(jButtonColor5, gridBagConstraints);

        jButtonColor2.setEnabled(false);
        jButtonColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 32, 7, 32);
        jPanelColor.add(jButtonColor2, gridBagConstraints);

        jButtonColor4.setEnabled(false);
        jButtonColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 32, 7, 32);
        jPanelColor.add(jButtonColor4, gridBagConstraints);

        jButtonColor6.setEnabled(false);
        jButtonColor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 32, 7, 32);
        jPanelColor.add(jButtonColor6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(jPanelColor, gridBagConstraints);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        jButtonBuy.setText("Comprar");
        jButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 11);
        jPanel7.add(jButtonBuy, gridBagConstraints);

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        jPanel7.add(jButtonCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jPanel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(3, 11, 3, 11);
        jPanel1.add(jLabel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public JButton getjButtonBuy() {
        return jButtonBuy;
    }

    public void setjButtonBuy(JButton jButtonBuy) {
        this.jButtonBuy = jButtonBuy;
    }

    public JComboBox getjComboBoxMarcas() {
        
        return jComboBoxMarcas;
    }

    public void setjComboBoxMarcas() {
        jComboBoxMarcas.setModel(miModelo.getMarcas());
    }

    public JSlider getjSlider1() {
        return jSlider1;
    }

    public void setjSlider1(JSlider jSlider1) {
        this.jSlider1 = jSlider1;
    }
    
    public void setjSlider1Value(int value){
        jSlider1.setValue(value);
    }

    public JTextField getjTextFieldPrecio() {
        return jTextFieldPrecio;
    }

    public void setjTextFieldPrecio(JTextField jTextFieldPrecio) {
        this.jTextFieldPrecio = jTextFieldPrecio;
    }
    
    

    public JButton getjButtonColor1() {
        return jButtonColor1;
    }

    public void setjButtonColor1(JButton jButtonColor1) {
        this.jButtonColor1 = jButtonColor1;
    }

    public JButton getjButtonColor2() {
        return jButtonColor2;
    }

    public void setjButtonColor2(JButton jButtonColor2) {
        this.jButtonColor2 = jButtonColor2;
    }

    public JButton getjButtonColor3() {
        return jButtonColor3;
    }

    public void setjButtonColor3(JButton jButtonColor3) {
        this.jButtonColor3 = jButtonColor3;
    }

    public JButton getjButtonColor4() {
        return jButtonColor4;
    }

    public void setjButtonColor4(JButton jButtonColor4) {
        this.jButtonColor4 = jButtonColor4;
    }

    public JButton getjButtonColor5() {
        return jButtonColor5;
    }

    public void setjButtonColor5(JButton jButtonColor5) {
        this.jButtonColor5 = jButtonColor5;
    }

    public JButton getjButtonColor6() {
        return jButtonColor6;
    }

    public void setjButtonColor6(JButton jButtonColor6) {
        this.jButtonColor6 = jButtonColor6;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjTextFieldPrecio() {
        jTextFieldPrecio.setText(String.valueOf(miModelo.getPrecio()));
    }
    
    public void setSeleccionMarca(){
        Object marcaSeleccionada = miModelo.getMarcaSeleccionada();
        jComboBoxMarcas.setSelectedItem(marcaSeleccionada);
    }
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        int [] value = {1,4};
        miControl.setSelectionButtonGroup1(value);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        int [] value = {4,5};
        miControl.setSelectionButtonGroup1(value);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        miControl.setjSlider1Value();
    }//GEN-LAST:event_jSlider1StateChanged

    private void jComboBoxMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcasActionPerformed
        miControl.setMarcaSelection();
    }//GEN-LAST:event_jComboBoxMarcasActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        int [] value = {5,6};
        miControl.setSelectionButtonGroup1(value);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        miControl.setjTextFieldValue();
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        miControl.restart();    
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyActionPerformed
        miControl.comprar();
    }//GEN-LAST:event_jButtonBuyActionPerformed

    private void jButtonColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor1ActionPerformed
        miControl.setColor(1);
    }//GEN-LAST:event_jButtonColor1ActionPerformed

    private void jButtonColor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor6ActionPerformed
        miControl.setColor(6);
    }//GEN-LAST:event_jButtonColor6ActionPerformed

    private void jButtonColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor2ActionPerformed
        miControl.setColor(2);
    }//GEN-LAST:event_jButtonColor2ActionPerformed

    private void jButtonColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor3ActionPerformed
        miControl.setColor(3);
    }//GEN-LAST:event_jButtonColor3ActionPerformed

    private void jButtonColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor4ActionPerformed
        miControl.setColor(4);
    }//GEN-LAST:event_jButtonColor4ActionPerformed

    private void jButtonColor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor5ActionPerformed
        miControl.setColor(5);
    }//GEN-LAST:event_jButtonColor5ActionPerformed

    public void setjButtonColor1Background(Color color){
        jButtonColor1.setBackground(color);
        jButtonColor1.setEnabled(true);
    }
    public void setjButtonColor2Background(Color color){
        jButtonColor2.setBackground(color);
        jButtonColor2.setEnabled(true);
    }
    public void setjButtonColor3Background(Color color){
        jButtonColor3.setBackground(color);
        jButtonColor3.setEnabled(true);
    }
    public void setjButtonColor4Background(Color color){
        jButtonColor4.setBackground(color);
        jButtonColor4.setEnabled(true);    
    }
    public void setjButtonColor5Background(Color color){
        jButtonColor5.setBackground(color);
        jButtonColor5.setEnabled(true);    
    }
    public void setjButtonColor6Background(Color color){
        jButtonColor6.setBackground(color);
        jButtonColor6.setEnabled(true);    
    }
    
    public void resetjButtonColorsBackground(){
        jButtonColor1.setEnabled(false);
        jButtonColor2.setEnabled(false);
        jButtonColor3.setEnabled(false);
        jButtonColor4.setEnabled(false);
        jButtonColor5.setEnabled(false);
        jButtonColor6.setEnabled(false);
    }
    
    public void setPanelTamañoEnable(){
        jPanelTamaño.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tamaño de pantalla"));
        jPanelTamaño.setEnabled(true);
    }
    
    public void setPanelTamañoDisabled(){
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
        buttonGroup1.clearSelection();
        jPanelTamaño.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Tamaño de pantalla"));
        jPanelTamaño.setEnabled(false);
    }
    
    public void setPanelColorEnable(){
        jPanelColor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Color"));
        jPanelColor.setEnabled(true);
    }
    public void setPanelColorDisabled(){
        resetjButtonColorsBackground();
        jPanelColor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Color"));
        jPanelColor.setEnabled(false);
    }
    
    public void setjRadioButton1Enabled(){
        jRadioButton1.setEnabled(true);
    }
    
    public void setjRadioButton2Enabled(){
        jRadioButton2.setEnabled(true);
    }
    
    public void setjRadioButton3Enabled(){
        jRadioButton3.setEnabled(true);
    }
    
    public void setjRadioButton1Disabled(){
        jRadioButton1.setEnabled(false);
    }
    
    public void setjRadioButton2Disabled(){
        jRadioButton2.setEnabled(false);
    }
    
    public void setjRadioButton3Disabled(){
        jRadioButton3.setEnabled(false);
    }
    
    public void clearButtonGroupSelection(){
        buttonGroup1.clearSelection();
    }
    
    public void ErrorjTextLabel(){
        jLabel3.setText("<html>El precio introducido no es un número, por favor introduzca un número, o utilice el cursor</html>");
    }
    
    public void clearErrorjTextLabel(){
        jLabel3.setText("");
    }
    
    public void setPanelMarcaDisabled(){
        jComboBoxMarcas.setSelectedItem(miModelo.getMarcaSeleccionada());
        jPanelMarca.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Marca"));
        jPanelMarca.setEnabled(false);
        jComboBoxMarcas.setEnabled(false);
    }
    
    public void setPanelMarcaEnabled(){
        jPanelMarca.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Marca"));
        jPanelMarca.setEnabled(true);
        jComboBoxMarcas.setEnabled(true);
    }
    
    public void ErrorCompra(){
        jLabel3.setText("<html>No ha terminado de seleccionar las caracteristicas de su movil.</html>");
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBuy;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonColor1;
    private javax.swing.JButton jButtonColor2;
    private javax.swing.JButton jButtonColor3;
    private javax.swing.JButton jButtonColor4;
    private javax.swing.JButton jButtonColor5;
    private javax.swing.JButton jButtonColor6;
    private javax.swing.JComboBox jComboBoxMarcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JPanel jPanelMarca;
    private javax.swing.JPanel jPanelPrecio;
    private javax.swing.JPanel jPanelTamaño;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
